version: "3.7"
services:
  db:
    image: postgres
    container_name: todolist-postgres
    restart: always
    volumes:
      - todolist-data:/data/postgresql
    ports:
      - 80:5432
    environment:
      - POSTGRES_DB:todolist
      - POSTGRES_USER:todolist
      - POSTGRES_PASSWORD:todolist

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://todolist:todolist@localhost:5432/todolist?schema=public
      - JWT_SECRET_KEY=1234
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  todolist-data:
    driver: local
